### ISSUE TITLE
Panic at 'received a message with a route that has no listeners' with wildcard channel subscriptions

### ISSUE THREAD

**Issue by parasyte** [pubnub/rust#38]
Use the example code from #37 but send a slightly different (valid/non-malformed) publish request:

```
$ curl 'https://ps.pndsn.com/publish/demo-36/demo-36/0/foo.bar/0/%22hello%22'
```

This will cause the program to panic in the subscribe loop.

<details><summary>Full trace log</summary>

```
$ RUST_LOG='trace' RUST_BACKTRACE=1 cargo run --package pubnub-hyper --example publish-subscribe
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/examples/publish-subscribe`
Subscribing...
[2020-03-04T22:49:21Z DEBUG pubnub_core::subscription::subscribe_loop_supervisor] Creating the subscribe loop
[2020-03-04T22:49:21Z DEBUG pubnub_core::subscription::subscribe_loop_supervisor] Waiting for subscription loop ready...
[2020-03-04T22:49:21Z DEBUG pubnub_core::subscription::subscribe_loop] Starting subscribe loop
[2020-03-04T22:49:21Z DEBUG pubnub_hyper::transport::hyper::util] URL: https://ps.pndsn.com/v2/subscribe/demo-36/foo%2E%2A/0?channel-group=&tt=0&tr=0
[2020-03-04T22:49:21Z TRACE hyper::client::pool] checkout waiting for idle connection: "https://ps.pndsn.com"
[2020-03-04T22:49:21Z TRACE hyper::client::connect::http] Http::connect; scheme=Some("https"), host=Some("ps.pndsn.com"), port=None
[2020-03-04T22:49:21Z DEBUG hyper::client::connect::dns] resolving host="ps.pndsn.com"
[2020-03-04T22:49:21Z DEBUG hyper::client::connect::http] connecting to 54.241.191.232:443
[2020-03-04T22:49:21Z TRACE mio::poll] registering with poller
[2020-03-04T22:49:21Z TRACE mio::sys::unix::kqueue] registering; token=Token(0); interests=Readable | Writable | Error | Hup
[2020-03-04T22:49:21Z DEBUG hyper::client::connect::http] connected to Some(V4(54.241.191.232:443))
[2020-03-04T22:49:21Z TRACE hyper::client::conn] client handshake HTTP/1
[2020-03-04T22:49:21Z TRACE hyper::client] handshake complete, spawning background dispatcher task
[2020-03-04T22:49:21Z TRACE want] signal: Want
[2020-03-04T22:49:21Z TRACE want] signal found waiting giver, notifying
[2020-03-04T22:49:21Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Busy }
[2020-03-04T22:49:21Z TRACE want] poll_want: taker wants!
[2020-03-04T22:49:21Z TRACE hyper::client::pool] checkout dropped for "https://ps.pndsn.com"
[2020-03-04T22:49:21Z TRACE hyper::proto::h1::role] Client::encode method=GET, body=None
[2020-03-04T22:49:21Z TRACE hyper::proto::h1::io] detected no usage of vectored write, flattening
[2020-03-04T22:49:21Z DEBUG hyper::proto::h1::io] flushed 95 bytes
[2020-03-04T22:49:21Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: KeepAlive, keep_alive: Busy }
[2020-03-04T22:49:21Z TRACE hyper::proto::h1::conn] Conn::read_head
[2020-03-04T22:49:21Z DEBUG hyper::proto::h1::io] read 284 bytes
[2020-03-04T22:49:21Z TRACE hyper::proto::h1::role] Response.parse([Header; 100], [u8; 284])
[2020-03-04T22:49:21Z TRACE hyper::proto::h1::role] Response.parse Complete(240)
[2020-03-04T22:49:21Z DEBUG hyper::proto::h1::io] parsed 7 headers
[2020-03-04T22:49:21Z DEBUG hyper::proto::h1::conn] incoming body is content-length (44 bytes)
[2020-03-04T22:49:21Z TRACE hyper::proto::h1::decode] decode; state=Length(44)
[2020-03-04T22:49:21Z DEBUG hyper::proto::h1::conn] incoming body completed
[2020-03-04T22:49:21Z TRACE hyper::proto::h1::conn] maybe_notify; read_from_io blocked
[2020-03-04T22:49:21Z TRACE want] signal: Want
[2020-03-04T22:49:21Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
[2020-03-04T22:49:21Z TRACE want] signal: Want
[2020-03-04T22:49:21Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
[2020-03-04T22:49:21Z TRACE hyper::client::pool] put; add idle connection for "https://ps.pndsn.com"
[2020-03-04T22:49:21Z DEBUG hyper::client::pool] pooling idle connection for "https://ps.pndsn.com"
[2020-03-04T22:49:21Z DEBUG pubnub_core::subscription::subscribe_loop] messages: []
[2020-03-04T22:49:21Z DEBUG pubnub_core::subscription::subscribe_loop] timetoken: Timetoken { t: 15833621473681046, r: 1 }
[2020-03-04T22:49:21Z DEBUG pubnub_hyper::transport::hyper::util] URL: https://ps.pndsn.com/v2/subscribe/demo-36/foo%2E%2A/0?channel-group=&tt=15833621473681046&tr=1
[2020-03-04T22:49:21Z TRACE hyper::client::pool] take? "https://ps.pndsn.com": expiration = Some(300s)
[2020-03-04T22:49:21Z DEBUG hyper::client::pool] reuse idle connection for "https://ps.pndsn.com"
[2020-03-04T22:49:21Z TRACE hyper::proto::h1::role] Client::encode method=GET, body=None
[2020-03-04T22:49:21Z DEBUG hyper::proto::h1::io] flushed 111 bytes
[2020-03-04T22:49:21Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: KeepAlive, keep_alive: Busy }
[2020-03-04T22:49:21Z TRACE hyper::client::pool] idle interval checking for expired
[2020-03-04T22:49:24Z TRACE hyper::proto::h1::conn] Conn::read_head
[2020-03-04T22:49:24Z DEBUG hyper::proto::h1::io] read 390 bytes
[2020-03-04T22:49:24Z TRACE hyper::proto::h1::role] Response.parse([Header; 100], [u8; 390])
[2020-03-04T22:49:24Z TRACE hyper::proto::h1::role] Response.parse Complete(241)
[2020-03-04T22:49:24Z DEBUG hyper::proto::h1::io] parsed 7 headers
[2020-03-04T22:49:24Z DEBUG hyper::proto::h1::conn] incoming body is content-length (149 bytes)
[2020-03-04T22:49:24Z TRACE hyper::proto::h1::decode] decode; state=Length(149)
[2020-03-04T22:49:24Z DEBUG hyper::proto::h1::conn] incoming body completed
[2020-03-04T22:49:24Z TRACE hyper::proto::h1::conn] maybe_notify; read_from_io blocked
[2020-03-04T22:49:24Z TRACE want] signal: Want
[2020-03-04T22:49:24Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
[2020-03-04T22:49:24Z TRACE want] signal: Want
[2020-03-04T22:49:24Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
[2020-03-04T22:49:24Z TRACE hyper::client::pool] put; add idle connection for "https://ps.pndsn.com"
[2020-03-04T22:49:24Z DEBUG hyper::client::pool] pooling idle connection for "https://ps.pndsn.com"
[2020-03-04T22:49:24Z DEBUG pubnub_core::subscription::subscribe_loop] messages: [Message { message_type: Publish, route: Some("foo.*"), channel: "foo.bar", json: Short("hello"), metadata: Null, timetoken: Timetoken { t: 15833621644928356, r: 1 }, client: None, subscribe_key: "demo-36", flags: 512 }]
[2020-03-04T22:49:24Z DEBUG pubnub_core::subscription::subscribe_loop] timetoken: Timetoken { t: 15833621644934806, r: 1 }
[2020-03-04T22:49:24Z DEBUG pubnub_core::subscription::subscribe_loop] route: foo.* (channel group)
thread 'main' panicked at 'received a message with a route that has no listeners', /Users/jay/projects/rust/pubnub-core/src/subscription/subscribe_loop.rs:250:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1053
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1428
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_failed
             at src/libcore/option.rs:1203
  14: core::option::Option<T>::expect
             at /rustc/6d69caba110c0c2fb90180df1cbc8be5033b91d4/src/libcore/option.rs:347
  15: pubnub_core::subscription::subscribe_loop::dispatch_messages::{{closure}}
             at ./pubnub-core/src/subscription/subscribe_loop.rs:250
  16: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/6d69caba110c0c2fb90180df1cbc8be5033b91d4/src/libstd/future.rs:44
  17: std::future::poll_with_tls_context
             at /rustc/6d69caba110c0c2fb90180df1cbc8be5033b91d4/src/libstd/future.rs:102
  18: pubnub_core::subscription::subscribe_loop::subscribe_loop::{{closure}}
             at ./pubnub-core/src/subscription/subscribe_loop.rs:159
  19: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/6d69caba110c0c2fb90180df1cbc8be5033b91d4/src/libstd/future.rs:44
  20: tokio::task::core::Core<T>::poll
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/task/core.rs:128
  21: tokio::task::harness::Harness<T,S>::poll::{{closure}}::{{closure}}
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/task/harness.rs:120
  22: core::ops::function::FnOnce::call_once
             at /rustc/6d69caba110c0c2fb90180df1cbc8be5033b91d4/src/libcore/ops/function.rs:232
  23: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/6d69caba110c0c2fb90180df1cbc8be5033b91d4/src/libstd/panic.rs:318
  24: std::panicking::try::do_call
             at /rustc/6d69caba110c0c2fb90180df1cbc8be5033b91d4/src/libstd/panicking.rs:303
  25: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  26: std::panicking::try
             at /rustc/6d69caba110c0c2fb90180df1cbc8be5033b91d4/src/libstd/panicking.rs:281
  27: std::panic::catch_unwind
             at /rustc/6d69caba110c0c2fb90180df1cbc8be5033b91d4/src/libstd/panic.rs:394
  28: tokio::task::harness::Harness<T,S>::poll::{{closure}}
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/task/harness.rs:101
  29: tokio::loom::std::causal_cell::CausalCell<T>::with_mut
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/loom/std/causal_cell.rs:41
  30: tokio::task::harness::Harness<T,S>::poll
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/task/harness.rs:100
  31: tokio::task::raw::poll
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/task/raw.rs:162
  32: tokio::task::raw::RawTask::poll
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/task/raw.rs:113
  33: tokio::task::Task<S>::run
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/task/mod.rs:371
  34: tokio::runtime::basic_scheduler::SchedulerPriv::tick
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/basic_scheduler.rs:203
  35: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/basic_scheduler.rs:143
  36: tokio::runtime::global::with_state::{{closure}}
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/global.rs:100
  37: std::thread::local::LocalKey<T>::try_with
             at /rustc/6d69caba110c0c2fb90180df1cbc8be5033b91d4/src/libstd/thread/local.rs:262
  38: std::thread::local::LocalKey<T>::with
             at /rustc/6d69caba110c0c2fb90180df1cbc8be5033b91d4/src/libstd/thread/local.rs:239
  39: tokio::runtime::global::with_state
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/global.rs:83
  40: tokio::runtime::global::with_basic_scheduler
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/global.rs:62
  41: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/basic_scheduler.rs:122
  42: tokio::runtime::Runtime::block_on::{{closure}}
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/mod.rs:419
  43: tokio::runtime::global::with_state::{{closure}}
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/global.rs:100
  44: std::thread::local::LocalKey<T>::try_with
             at /rustc/6d69caba110c0c2fb90180df1cbc8be5033b91d4/src/libstd/thread/local.rs:262
  45: std::thread::local::LocalKey<T>::with
             at /rustc/6d69caba110c0c2fb90180df1cbc8be5033b91d4/src/libstd/thread/local.rs:239
  46: tokio::runtime::global::with_state
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/global.rs:83
  47: tokio::runtime::global::with_basic_scheduler
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/global.rs:62
  48: tokio::runtime::basic_scheduler::Spawner::enter
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/basic_scheduler.rs:174
  49: tokio::runtime::spawner::Spawner::enter
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/spawner.rs:30
  50: tokio::runtime::handle::Handle::enter::{{closure}}::{{closure}}
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/handle.rs:36
  51: tokio::time::clock::Clock::enter
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/time/clock.rs:30
  52: tokio::runtime::time::variant::with_default
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/time.rs:43
  53: tokio::runtime::handle::Handle::enter::{{closure}}
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/handle.rs:36
  54: tokio::runtime::blocking::pool::Spawner::enter::{{closure}}
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/blocking/pool.rs:194
  55: std::thread::local::LocalKey<T>::try_with
             at /rustc/6d69caba110c0c2fb90180df1cbc8be5033b91d4/src/libstd/thread/local.rs:262
  56: std::thread::local::LocalKey<T>::with
             at /rustc/6d69caba110c0c2fb90180df1cbc8be5033b91d4/src/libstd/thread/local.rs:239
  57: tokio::runtime::blocking::pool::Spawner::enter
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/blocking/pool.rs:179
  58: tokio::runtime::handle::Handle::enter
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/handle.rs:33
  59: tokio::runtime::Runtime::block_on
             at /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/mod.rs:416
  60: publish_subscribe::main
             at pubnub-hyper/examples/publish-subscribe.rs:10
  61: std::rt::lang_start::{{closure}}
             at /rustc/6d69caba110c0c2fb90180df1cbc8be5033b91d4/src/libstd/rt.rs:67
  62: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  63: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  64: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  65: std::panicking::try
             at src/libstd/panicking.rs:281
  66: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  67: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  68: std::rt::lang_start
             at /rustc/6d69caba110c0c2fb90180df1cbc8be5033b91d4/src/libstd/rt.rs:67
  69: publish_subscribe::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2020-03-04T22:49:24Z TRACE want] signal: Want
[2020-03-04T22:49:24Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
[2020-03-04T22:49:24Z DEBUG pubnub_core::subscription::subscription] Dropping Subscription: Channel("foo.*")
[2020-03-04T22:49:24Z TRACE mio::poll] deregistering handle with poller
[2020-03-04T22:49:24Z TRACE want] signal: Closed
```
</details>

This is caused by a misclassification of wildcard channels as a group.

**Comment by MOZGIII** [comment]
Good catch!

I've been working on the infrastructure that should allow us to solve this issue as part of #35. I'll address this after we merge the #35 (after I'm able to push the code to that branch again :laughing: ).

**Comment by MOZGIII** [comment]
Fixes arrived to `master`, closing this.
